### PR TITLE
Add the ability to provide a class namespace in the JSON file. 

### PR DESCRIPTION
**Pull request by blocklogic-au**
This enables modules to be logically organized in the Modules directory.

### CODE REVIEW

**Comment by dcblogdev** [comment]
Can you expand on this, I don't understand its purpose

**Comment by solomon-ochepa** [comment]
> This enables modules to be logically organized in the Modules directory.

Sorry to say, but your code doesn't add any value. Consider working on more pressing needs or making the code more efficient.

Talking about ` logically organized in the Modules directory,` don't forget that folders will always be displayed in asc (A-Z) order. You can't sort them in the dir.

**Comment by blocklogic-au** [comment]
Sorry for the poor explanation.

In the application I am in the process of building there will potentially be hundreds of modules.

I need to be able to organise them in the directory.

Please see the attached screenshot

image

**Comment by solomon-ochepa** [comment]
> Sorry for the poor explanation.
> 
> In the application I am in the process of building there will potentially be hundreds of modules.
> 
> I need to be able to organize them in the directory.
> 
> Please see the attached screenshot
> 
> image

And, if I may ask, where did you derive this structure from? What/where are the actual modules here? I recognize the `Api,` `Crm,` and `TestModule;` still, I'm confused about the expanded Crm/ dir.

Why the `Crm/Zoho/ZohoCrm/` against the conventional `Crm/`?

**Comment by solomon-ochepa** [comment]
Why not create a `ZohoCrm` module if that aligns with your goal?

**Comment by dcblogdev** [comment]
I'm struggling to understand how this helps to organise the modules, can you explain further or publish a demo repo?

**Comment by solomon-ochepa** [comment]
I believe he is struggling with file/folder structuring.

**Comment by dcblogdev** [comment]
I'm closing this since there's been no response for awhile.

**Comment by human-pixel** [comment]
Hi All.

I am just now able to return to this project. 

I need to be able to organise many (potentially hundreds in time) modules in nested directories / namespaces. 

EG Crm/ZohoCrm, Crm/SalesForce, Crm/SomeOtherCrm

Users/RoleManager
Users/UserManager

If that is not possible, then I guess Ill just have to name them and deal with a single directory. 

Thanks
Ben

**Pull request closed without merging**
