### PR TITLE
Command signature patch

### PR DESCRIPTION
**Pull request by msztorc**
- Updated command stub (changed property $name to $signature)
- Updated test snapshots

### CODE REVIEW

**Comment by nWidart** [comment]
Great, thanks!
Thanks for fixing the tests too 👍

**Comment by lindo-llc** [comment]
Why was this needed?

**Comment by msztorc** [comment]
Property `$signature` is more appropriate than `$name` because except defining the command name, it allows you also to use named options like: `{--queue=}`

Additionally, `$signature` property is added by default in Laravel commands, see here: https://laravel.com/docs/8.x/artisan

**Comment by nWidart** [comment]
I prefer the "old" way of writing the signatures, but I agree this is the default now so.. 🤷‍♂️

**Pull request merged**
