### PR TITLE
Update config.php

### PR DESCRIPTION
**Pull request by solomon-ochepa**
Remove repeated replacement key for `routes/api`

### Optimizations
The following modifications enhance clean code and readability.
* Enabled  the `app/Models/` path generator: if the `database/*` paths are enabled by default, then the `app/Models/` needs to be enabled to comply with the MVC architecture.
* Remove whitespace between comments and properties.
* Convert comments to standard multi lines comment format.

### CODE REVIEW

**Comment by dcblogdev** [comment]
The only thing of value in this PR is removing the duplicate replacement. Changing the comments adds no value, modules does not need to be enabled by default when a module is generated the models folder will be created automatically. You can use seeder without a model if you wanted to.

**Comment by solomon-ochepa** [comment]
> The only thing of value in this PR is removing the duplicate replacement. Changing the comments adds no value, modules does not need to be enabled by default when a module is generated the models folder will be created automatically. You can use seeder without a model if you wanted to.
> 
> 

Code is poetry! The cleaner the code get, the easier it will be to read and understand.

The comments formatting truly doesn't add any functional values to the project, but it makes the code more comprehensive.

Comments are naturally followed by its property, once a whitespace come in between, it alter the meaning!

For the app/Models, I enabled it for readability purpose. If the database/seeders, factory & migrations are enabled by default then the models has to follow suit, in order to comply with the MVC architecture.

While reading the config file, it should make a meaning.

All the paths will be created when the appropriate commands are use, but the context itself should be self explanatory.

**Comment by dcblogdev** [comment]
I've closed this as I'm not going to argue with you about the comments, whichever style they are really makes little difference they just as readable with | or * I raise this in my reply and you relied to defend it.

If you want to use * and have models generated go ahead. The config can live that way in anyone projects just fine.

I'm spending most of my time trying to get the docs updated, demos and features out so I really don't have time to argue where a comment should be a | or a *

**Comment by solomon-ochepa** [comment]
@dcblogdev @alissn can you boldly tell us that clean and readable code are a thing of concern here?

Your response will guard us in our subsequent contributions!

Thank you.

**Comment by solomon-ochepa** [comment]
> I've closed this as I'm not going to argue with you about the comments, whichever style they are really makes little difference they just as readable with | or * I raise this in my reply and you relied to defend it.
> 
> If you want to use * and have models generated go ahead. The config can live that way in anyone projects just fine.
> 
> I'm spending most of my time trying to get the docs updated, demos and features out so I really don't have time to argue where a comment should be a | or a *

I'm not making PR to start arguments!

We all understand your schedule at the moment, and really appreciate you for the tasks.

You could have kindly make a review and request for a fix/update to meet up with expected standards.

I'm the director of ICT and the lead developer in my organization currently. I'm as busy as anyone can ever be, but I still sacrifice little time to contribute to this project all the time.

If this PR doesn't meet the standards or your expectations, then it's okay. I understand not everything will be accepted into the project!

Thank you.

**Comment by dcblogdev** [comment]
okay, I'll re-open please revert and remove the duplicate replacement.

**Comment by alissn** [comment]
@solomon-ochepa,

This package for the [laravel-framework](https://github.com/laravel/framework). Can you point me to a config file in the framework that resembles this structure?

If you believe that making changes for improved readability and cleanliness is beneficial, please consider implementing them in the framework.

**Comment by dcblogdev** [comment]
I've updated the config now, everything I don't want so closing this PR.

**Comment by solomon-ochepa** [comment]
It's okay, thanks.

**Pull request closed without merging**
