### PR TITLE
Add database management feature

### PR DESCRIPTION
**Pull request by lamtranb**
It's a newer version of #1163.

- [x]  Add database management feature
- [x]  Add command for migrating modules from .json to db
- [x]  Add publish migration
- [x]  Add Unit Tests
- [x] Add version, keep module.json file

### CODE REVIEW

**Comment by dcblogdev** [comment]
thanks! this looks great I'll check it out today.

**Comment by lamtranb** [comment]
Hi, do we have any update on this?

**Comment by jisheng100** [comment]
Great work. I also need this feature. Thanks for your contribution.

When will it be released?

**Comment by dcblogdev** [comment]
I'm tying to use this on an existing project to get a feel for it.

I've completed these steps,

Using your branch for testing.

I've updated the config file to include the MigrateFileToDatabaseCommand command in the list of commands array and added the config options:

```php
'activator'       => 'database_management',

'database_management' => [
    'enabled' => false,
    'update_file_to_database_when_updating' => true, // Option to update module.json into database when updating a module.
    'repository' => null
],

'default_version' => '1.0.0'
```

When I run  module:migrate-to-databas I get:

```
dave@dcblog ~/s/p/dcblog> a module:migrate-to-databas                                                                                            feature/ckeditor5!?

   ErrorException 

  Trying to access array offset on value of type null

  at /Users/dave/sites/not-parked/packages/laravel-modules/src/LaravelModulesServiceProvider.php:61
     57▕             return new Laravel\LaravelFileRepository($app, $path);
     58▕         });
     59▕         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
     60▕             $activator = $app['config']->get('modules.activator');
  ➜  61▕             $class = $app['config']->get('modules.activators.' . $activator)['class'];
     62▕ 
     63▕             if ($class === null) {
     64▕                 throw InvalidActivatorClass::missingConfig();
     65▕             }

  1   /Users/dave/sites/not-parked/packages/laravel-modules/src/LaravelModulesServiceProvider.php:61
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Trying to access array offset on value of type null", "/Users/dave/sites/not-parked/packages/laravel-modules/src/LaravelModulesServiceProvider.php")

      +6 vendor frames 
  8   /Users/dave/sites/not-parked/packages/laravel-modules/src/Module.php:73
      Illuminate\Container\Container::offsetGet("Nwidart\Modules\Contracts\ActivatorInterface")
dave@dcblog ~/s/p/dcblog> a module:migrate-to-databas  
```

**Comment by lamtranb** [comment]
Hi @dcblogdev 

Thanks for your feedback.

Please keep this

```
'activator'       => 'file',
```

And you just need to update:

```
'database_management' => [
    'enabled' => true,
    'update_file_to_database_when_updating' => true, // Option to update module.json into database when updating a module.
    'repository' => null // or using your own example: ModuleRepository::class
],
```
Because this feature is still needed file activator to scan all composer.json files in every package and insert into database.

Many thanks.

**Comment by dcblogdev** [comment]
Thanks, I've updated my config:

```php
'activator'       => 'file',

    'database_management' => [
        'enabled' => true,
        'update_file_to_database_when_updating' => true, // Option to update module.json into database when updating a module.
        'repository' => null // or using your own example: ModuleRepository::class
    ],
```

ran the command again and I get:

```
dave@dcblog ~/s/p/dcblog> a module:migrate-to-databas                                                                                          1 feature/ckeditor5!?

   Error 

  Call to a member function toArray() on array

  at /Users/dave/sites/not-parked/packages/laravel-modules/src/Laravel/LaravelDatabaseRepository.php:130
    126▕         $modules = [];
    127▕ 
    128▕         foreach ($cached as $moduleEntity) {
    129▕             $module = $this->createModule($this->app, $moduleEntity['name'], $moduleEntity['path']);
  ➜ 130▕             $module->setAttributes($moduleEntity->toArray());
    131▕             $modules[$moduleEntity['name']] = $module;
    132▕         }
    133▕ 
    134▕         return $modules;

  1   /Users/dave/sites/not-parked/packages/laravel-modules/src/FileRepository.php:173
      Nwidart\Modules\Laravel\LaravelDatabaseRepository::formatCached([])

  2   /Users/dave/sites/not-parked/packages/laravel-modules/src/Laravel/LaravelDatabaseRepository.php:156
      Nwidart\Modules\FileRepository::all()
```

**Comment by lamtranb** [comment]
Hi @dcblogdev 

Could you please clear the cache and remove the **modules** table in the database and try again to see if it works? Usually I run this with fresh install, not really check with an existing project with existing database tables.

Thanks.

**Comment by dcblogdev** [comment]
Sorry the same error. The table is empty as the error runs before anything can be saved.

I wanted to see if it can be back filled onto existing projects as I'm sure there is be a demand for that

**Comment by lamtranb** [comment]
Hi @dcblogdev 

I will take a look at this and get back to you soon.

Thanks.

**Comment by dcblogdev** [comment]
Brill, thanks!

**Comment by lamtranb** [comment]
Hi @dcblogdev

I have fixed the issue in the latest commit. The root cause is I did not checked the compatible between file and database cache.

I have a concern when we do a command, it still loads the boot method in src/Providers/BootstrapServiceProvider.php

```php
$this->app[RepositoryInterface::class]->boot();
```

And in our case, we use cache and just change the config to true:

```php
    /**
     * Use database management, not using module.json and modules_statuses.json.
     */
    'database_management' => [
        'enabled' => true,
        'update_file_to_database_when_updating' => true, // Option to update module.json into database when updating a module.
        'repository' => null
    ],
```

So if we do this, we have to clear the cache manually. But everytime we call the cache:clear command, it still goes through the boot all modules event first with the old data (in our case, it's file cache data, not the real database cache data). I think if we do some specific commands, we should exclude this behavior (I can do this). What do you think about it? I have left comments on this: https://github.com/nWidart/laravel-modules/pull/1513/commits/9b6c32fd0a9b29c8f37e1ab2c49e54e10b25e3d6

Could you please review it ?

Many thanks.

**Comment by dcblogdev** [comment]
I'm at LaraconEU I'll review it over the weekend, thanks 😊

**Comment by dcblogdev** [comment]
Hi, I've re-run the migrate existing modules. This does work and adds them to the database.

**okay, a few questions:**

1) I see the version in the config, how is that to be used? I know it adds a version into the db table but can you expand on its use?

2) After I've enabled`database_management` to true and then later changed it to false then the `module_statuses.json` file should take precedence I noticed if you disable a module when in database mode then switch to config mode and try to enable the module using the config file the module stays disabled. 

3) Maybe this is actually expected behaviour, when using the command `module:enable {module}` it does enable the module so maybe this is fine.

4) If I wanted to enable/disable modules from PHP to interact with the database how could you refresh the cache from PHP?

**Comment by dcblogdev** [comment]
> So if we do this, we have to clear the cache manually. But everytime we call the cache:clear command, it still goes through the boot all modules event first with the old data (in our case, it's file cache data, not the real database cache data). I think if we do some specific commands, we should exclude this behavior (I can do this). What do you think about it? I have left comments on this: [9b6c32f](https://github.com/nWidart/laravel-modules/commit/9b6c32fd0a9b29c8f37e1ab2c49e54e10b25e3d6)
> 
> Could you please review it ?

Yes that looks fine to me.

**Comment by dcblogdev** [comment]
@lamtranb if you can answer the above questions that would help me to understand this solution.

thanks.

**Comment by lamtranb** [comment]
> @lamtranb if you can answer the above questions that would help me to understand this solution.
> 
> thanks.

Hi @dcblogdev 

Sorry for late response. I'm still working on this. I will get back to you ASAP.

**Comment by lamtranb** [comment]
The updates will be ready in the next few weeks.

**Comment by lamtranb** [comment]
up

**Comment by lamtranb** [comment]
Hi @dcblogdev ,

I rebased but the UTs has failed, do we have any branch with the working UTs ?

**Comment by lamtranb** [comment]
Hi @dcblogdev , 

It's been a long time. Looks like the UTs from master are still failing, so I'll go ahead and answer the questions.

> 1. I see the version in the config, how is that to be used? I know it adds a version into the db table but can you expand on its use?
I give us a setting "update_file_to_database_when_updating" to support the case: When an user wants to update the module/module.json manually, example they update version 1.0.1 on module.json (in db, the version is 1.0.0), then they run update => the version from file will update into database automatically. If "update_file_to_database_when_updating" is off, then no update from module.json to database. In my project, I use this when we export our modules and install/uninstall or upgrade our module.

> 2. After I've enabled`database_management` to true and then later changed it to false then the `module_statuses.json` file should take precedence I noticed if you disable a module when in database mode then switch to config mode and try to enable the module using the config file the module stays disabled.

> 3. Maybe this is actually expected behaviour, when using the command `module:enable {module}` it does enable the module so maybe this is fine.

I will answer 2 + 3 into this one. Currently, when switching to database management, I don't use the module_statuses.json. Could you provide the me correct expected behavior ?

> 4. If I wanted to enable/disable modules from PHP to interact with the database how could you refresh the cache from PHP?

I quite don't understand this question. Could you please check src/Laravel/DatabaseModule.php - setActive? Both enable/disable should go through this method and flush all the cache. There are issues when switching between database and file management that I already fixed it. Could you please re-test this step again?

> 5. why would you need your own repository class? what's the use case?

In my cases, I have custom modules table with additional fields, and I want to extend some methods from the base repository, so I provide a way to implement own our repository. Do you think it's necessary? If not, I can remove it. Please share me your view.

**Comment by dcblogdev** [comment]
FYI I'm doing more testing on today, sorry for the lack of communication been really busy.

Tests are now passing, this is looking great, going to try this out on an existing modules installation I have.

**Comment by dcblogdev** [comment]
Could you have a look at the caching, new modules / migrations don't seem to be picked up unless I run `module:migrate-to-database` again 

on a bigger project all my tests are failing due to no such table: modules but works manually as I have migrated. My tests use a RefreshDatabase trait. So the modules migration should be picked up and ran.

**Comment by lamtranb** [comment]
> Could you have a look at the caching, new modules / migrations don't seem to be picked up unless I run `module:migrate-to-database` again
> 
> on a bigger project all my tests are failing due to no such table: modules but works manually as I have migrated. My tests use a RefreshDatabase trait. So the modules migration should be picked up and ran.

Hi, thanks for your feedback. Don't worry I am busy too. I just rebase and I'm glad all the tests are green.

Based on my understanding, we have to run `module:migrate-to-database` to make it work (manually). If you want an automatic way, could you provide me a good solution then I will update the code for you. But I think we should force developers to run this command whenever they need to switch to database management.

If I misunderstand what you said, could you please provide reproduce steps that caused the issue? Thanks.

**Comment by dcblogdev** [comment]
okay, doing it manually may be fine to do, I'll do some further testing to show repeatable steps if needed.

**Comment by dcblogdev** [comment]
I've put together a demo containing 1 module called Demo, it has a test to checks the for a 200 when hitting /demo

it works when database_management is disabled but when enabled it gets a 404 but the route is listed inside `route:list` and also loads in the browser its just not being found in tests but works when database_management is disabled.

https://github.com/dcblogdev/modules-demo-temp

this repo loads the modules package locally, which uses your branch. Let me know If I'm missing anything to get this working.

**Comment by lamtranb** [comment]
Sorry for late response, I will check this ASAP.

**Pull request closed without merging**
