### PR TITLE
Added possibility to update all modules at once if any not specified.

### PR DESCRIPTION
**Pull request by SpinyMan**

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

Thank you for the contribution!
Can you make sure to use spaces instead of tabs, please?

**Comment by nWidart** [comment]
Thank you!

**Comment by SpinyMan** [comment]
Sorry man, when could I see it? my composer still have no updates (version 1.27)

**Comment by nWidart** [comment]
This was released in 3.0 https://github.com/nWidart/laravel-modules/releases

**Comment by SpinyMan** [comment]
And? what about old versions? I use 1.27 & I want to be in trend) Pease update all versions!

**Comment by nWidart** [comment]
1.27 is almost a year old and is not supported. 
New features and fixes get added to new versions otherwise we wouldn't have versions :D

**Comment by SpinyMan** [comment]
> This was released in 3.2 https://github.com/nWidart/laravel-modules/releases

Sorry, man, but I can't find it there... No code needed in version 3 or 2... Please review your code (v3.2) and update ASAP.
Thank you!

**Comment by nWidart** [comment]
Aha I see the issue, you submitted the pull request to the 1.0 branch.

**Comment by SpinyMan** [comment]
> you submitted the pull request to the 1.0 branch

So, any suggestions when this PR will be integrated into last branch?

**Comment by nWidart** [comment]
The easiest would be if for you to send the same PR on the master branch.

If not when I have time to look into it 😄

**Comment by SpinyMan** [comment]
Hello, any updates?

**Pull request merged**
