### PR TITLE
Ability to delete multiple modules

### PR DESCRIPTION
**Pull request by solomon-ochepa**
Added the ability to delete multiple modules at once.

### Delete a Module
```
php artisan module:delete Module1
```

### Delete Multiple Modules
```
php artisan module:delete Module1 Module2 Module3
```

### CODE REVIEW

**Comment by dcblogdev** [comment]
This is going to need a test to confirm single and multiple modules can be deleted.

Have a look at `tests/Commands/ModuleDeleteCommandTest`

**Comment by solomon-ochepa** [comment]
> This is going to need a test to confirm single and multiple modules can be deleted.
> 
> Have a look at `tests/Commands/ModuleDeleteCommandTest`

I understand the important of writing a test file, but it shouldn't be mandatory to make a contribution. I can't create a test if you've been following my works closely.

Nevertheless, I've incorporated the changes to my system and have been using the feature for a while now.

It wouldn't be bad if anyone else write the test, pending when I'll get my environment fixed.

Thanks.

**Comment by dcblogdev** [comment]
okay no worries, I can look at adding a test shortly.

**Comment by solomon-ochepa** [comment]
> okay no worries, I can look at adding a test shortly.

Thanks for your understanding.

**Comment by dcblogdev** [comment]
Can you upgrade this, I've just merged another PR that updated the DeleteCommand file to use Laravel Prompt

**Comment by solomon-ochepa** [comment]
Wow, I just pulled the recent update. This PR is not necessary anymore.

From the recent update, multiple modules can now be deleted successfully.

So, I'll be closing this PR now.

**Pull request closed without merging**
