### PR TITLE
Add generate mailable command.

### PR DESCRIPTION
**Pull request by mikemand**

### CODE REVIEW

**Comment by nWidart** [comment]
Could you add a test for this please ? :)

**Comment by mikemand** [comment]
Sure thing.

**Comment by mikemand** [comment]
It looks like Travis wasn't able to make the Module on set-up. Should I not try to use the same Module name as another test?

**Comment by nWidart** [comment]
Thank you! 😄

**Comment by JulienTant** [comment]
This PR has broken everything o_o

**Comment by mikemand** [comment]
That's helpful. Can you explain what is broken? I've tested it and there were no problems creating a new Mailable.

**Pull request merged**
