### PR TITLE
Test command

### PR DESCRIPTION
**Pull request by SpinyMan**
run command (module:test) for all modules or specified one.

### CODE REVIEW

**Comment by spinyman** [comment]
Have you any problems with merge it?

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply. I've looked at your PR but I don't see a good reason to add this. It's already easy to use phpunit directly to run module tests.
You can view an [example phpunit config file here](https://github.com/AsgardCms/Platform/blob/3.0/phpunit.xml), test separate test suits are optional.

**Comment by SpinyMan** [comment]
ok. if you think it's a best way - let it be.

**Comment by nWidart** [comment]
Hi,

I'll close this to the before mentioned reason. I don't see a good use case for this over using phpunit itself.

**Pull request closed without merging**
