### PR TITLE
Update api.stub

### PR DESCRIPTION
**Pull request by solomon-ochepa**
Formatted.

### CODE REVIEW

**Comment by solomon-ochepa** [comment]
If I may ask, why was this PR closed without being merged?

**Comment by dcblogdev** [comment]
there is not a v1 group out the box, it would be better to the namespace but omit the prefix

**Comment by solomon-ochepa** [comment]
> there is not a v1 group out the box, it would be better to the namespace but omit the prefix

The `v1` is a versioning system, which is recommended and a standard for all API resources.

**Comment by solomon-ochepa** [comment]
> > there is not a v1 group out the box, it would be better to the namespace but omit the prefix
> 
> The `v1` is a versioning system, which is recommended and a standard for all API resources.

API responses may change from time to time, and the best way to keep track is with the versioning system; `v1`, `v2`, `v3`, etc.

This feature might not be built into this package from the beginning, but that doesn't mean standard can't be recommended.

Thanks.

**Comment by dcblogdev** [comment]
I agree, I was thinking that the versions are coded into the route provider, which they're not I forgot as that's how I normally structure my API's.

**Comment by solomon-ochepa** [comment]
> there is not a v1 group out the box, it would be better to the namespace but omit the prefix

Please, before you close any PR next time, always think about the needs of others.

The fact that a PR doesn't apply to your specific needs or expectations doesn't mean the community doesn't need it. Always think, putting the community first.

**Pull request merged**
