### PR TITLE
added views tag to ServiceProvider stub

### PR DESCRIPTION
**Pull request by jnbn**
for easy calling from artisan like

```
php artisan vendor:publish --provider="YourNamespace\YourServiceProvider" --tag="views"
```

### CODE REVIEW

**Comment by nWidart** [comment]
Hello & thanks for the contribution.
Please update the corresponding [snapshots](https://github.com/nWidart/laravel-modules/tree/master/tests/Commands/__snapshots__)

**Comment by bloggervista** [comment]
You mean failing tests right?

**Comment by nWidart** [comment]
yes

**Comment by bloggervista** [comment]
Its passed now.

**Pull request merged**
