### PR TITLE
fix module:seed --class

### PR DESCRIPTION
**Pull request by Instanced**
Example:
`php artisan module:seed User --class=UserSeeder`

### CODE REVIEW

**Comment by Instanced** [comment]
@nWidart #509

**Comment by nWidart** [comment]
And?

**Comment by Instanced** [comment]
@nWidart This Pull requests mainly fixes the problem that `module:seed` doesn't work, and generates a class to module's seeds directory.

**Comment by nWidart** [comment]
That still doesn't explain my question, but I'll try it out myself. 

Thanks for the contribution. 👍

**Pull request merged**
