### PR TITLE
Feature/submodule support

### PR DESCRIPTION
**Pull request by Hodel1**
Creating Submodules like: Admin/Auth, Admin/User, Core/Configuration, etc.

### CODE REVIEW

**Comment by Hodel1** [comment]
now i fixed that php unit errors :)

**Comment by dcorazolla** [comment]
Good idea... Exactly what i need!

**Comment by mshamaseen** [comment]
Why hasn't this merged? Any problem with it? I was about to do a PR for this feature.

**Comment by mshamaseen** [comment]
I've just tried this, this DOESN'T work.

**Pull request closed without merging**
