### PR TITLE
Lumen 5.5.x support ( Removed mixed Laravel and Lumen dependencies )

### PR DESCRIPTION
**Pull request by deividaspetraitis**
See https://github.com/nWidart/laravel-modules/pull/355

-  PR with the up to date upstream
-  Fixed class import of the AliasLoader

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks!

What's this public_path helper you added? Is it the same as laravel's one, for lumen?

**Comment by deividaspetraitis** [comment]
That's right. By default lumen doen't have such helper function and throws errors because of this that's why I added it.

**Comment by nWidart** [comment]
I see, thanks.

**Comment by deividaspetraitis** [comment]
Thanks!

**Pull request merged**
