### PR TITLE
[fix] fix stubs composer for app_folder

### LINKED ISSUE #1821: Custom modules.paths.app_folder value not working
image
When the `config/modules.php` value for `modules.paths.app_folder` is changed (from the default `app/` to `src/` for instance), the module will be generated using the old namespace format with the `app\` path in lowercase.

image
The module `composer.json` didn't reflect the custom app_folder, it's still using `app/`.

image
The Service Provider and every other class were created with the wrong namespace. All the namespaces have the initial `app\` segment and are in lowercase.

The custom app_folder `'src/'` wasn't generated, instead the `'app/'` is used.

Is there any workaround for this, please?
@nWidart @dcblogdev @alissn 

Thanks for the love.

### PR DESCRIPTION
**Pull request by alissn**
fix #1821

update stubs composer.json to read app_folder_name from config on create new module

### CODE REVIEW

**Comment by dcblogdev** [comment]
Noticed this does not work if the value 'APP_FOLDER_NAME', is not present in the config file.

Don't think there is a workaround to be put in place.

**Comment by dcblogdev** [comment]
ah I've got a fix will for a PR for this shortly.

**Comment by alissn** [comment]
@dcblogdev, thank you for fixing that. I forgot to check for this bug.🙏

I've been very busy this week and haven't had time to review GitHub.

**Comment by dcblogdev** [comment]
no problem, I've got a bit more time on my hands to trying to get through the Pr's and issues a bit more.

**Pull request merged**
