### PR TITLE
Database Modules

### LINKED ISSUE #1084: Configurable option for file or migration
Hi! 
Let me start off by saying that this package is **VERY** helpful. However, I'm seeing a little problem with the `modules_statuses.json`. The issue that I'm facing is that is it hard to reach for customization on a product, like a shop system e.g. Blesta. I'd like to see a config option for having the module statuses in a database table or a file like `modules_statuses.json`

### PR DESCRIPTION
**Pull request by FoksVHox**
This PR implements a feature that allows for using a database table to manage your modules. Nicolas created an old branch with most of the progress done, I've picked it up today, with a fork. 

Todo:
- [ ] Modify the ModuleGenerator to respect the database table
- [ ] Add command for migrating modules from `.json` to db

Fixes #1084 
Co-Authored-By: Nicolas Widart <n.widart@gmail.com>

### CODE REVIEW

**Comment by FoksVHox** [comment]
@nWidart Could give a helping hand? I really don't know why it's erroring...

**Comment by lamtranb** [comment]
Hello @FoksVHox 
When I searched how to use a database table to manage modules and this came up.
I checked the PR but sorry the work is not done yet, maybe 70-80%, and UT too. That's why it failed.

**Comment by FoksVHox** [comment]
> Hello @FoksVHox
> When I searched how to use a database table to manage modules and this came up.
> I checked the PR but sorry the work is not done yet, maybe 70-80%, and UT too. That's why it failed.

I'm fully aware of it wasn't finished. And I'm trying to figure out why it fails, as it doesn't make sense to me why it does.

> and UT too. That's why it failed.

What do you mean by that?

**Comment by lamtranb** [comment]
Hello @FoksVHox

> > and UT too. That's why it failed.
> 
> What do you mean by that?

I mean Unit Test is not correct. You can check it in [`here`](https://travis-ci.org/github/nWidart/laravel-modules/jobs/750825190). We have 3 errors in Unit Test. The code should not find DisabledModule's module.json because it does not exist. 
I forked your work and I will try to work on it because I need this feature too.

**Comment by FoksVHox** [comment]
Closed in favor of #1163

**Pull request closed without merging**
