### PR TITLE
Only Register Factories when Running in Console

### PR DESCRIPTION
**Pull request by nmfzone**
I think this approach can reduce the application to load the unused file when running in browser.

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks, good idea! 👌

**Comment by nmfzone** [comment]
Sure 👌
But, I'm not sure why Travis CI fails. I think you should update the tests snapshot.

**Comment by nWidart** [comment]
Indeed, that's something you need to run on your end.

**Comment by nmfzone** [comment]
@nWidart Ohh, I see..on my way.

**Comment by nWidart** [comment]
Thanks!

**Pull request merged**
