### PR TITLE
Features/module factories

### PR DESCRIPTION
**Pull request by mohamed-aiman**
- added factory to config
- changed factories path from 
**project/Modules/ModuleName/Providers/Database/factories** to **project/Modules/ModuleName/Database/factories**
- changed **factories** to **Factories** for consistency, as by default other folders like Seeders,Migrations are named and others are named that way.

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks for the contribution!

Good catch for the location of factories!
From the diff I see `'factory' => 'Database/Factories',` was added, not changed, so it wasn't present before. Is this value used, or is it just as reference?

**Comment by mohamed-aiman** [comment]
It's used and it works perfectly. while the module is generated and empty folder with keep is generated. I think its good to keep. :)

**Comment by nWidart** [comment]
It looks like you're not up to date with latest changes. https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L99 has a different structure.

**Comment by nWidart** [comment]
And it also looks like the relative path issue was fixed too: https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/scaffold/provider.stub#L100

**Comment by mohamed-aiman** [comment]
I have seen that. I think thats for the major version for php 7 and Larave >=5.5. I fixed it for version 1.0 which is used by php 5 > 7 and Laravel 5.4.

**Comment by nWidart** [comment]
I see, 1.0 is not maintained anymore so you'll have to upgrade to version 2 to have this fix.

**Comment by mohamed-aiman** [comment]
Cool 😊

**Pull request closed without merging**
