### PR TITLE
Only support supported Laravel versions

### PR DESCRIPTION
**Pull request by FoksVHox**

### CODE REVIEW

**Comment by mauriciovillam** [comment]
I see why, but why?

**Comment by FoksVHox** [comment]
> I see why, but why?

Cause it doesn't make sense to support unsupported laravel versions, that's dumb

**Comment by mauriciovillam** [comment]
Sorry, I may be seeing things wrongly but I don't see in which way a compatible versions cheatsheet is dumb or why this pull request is necessary.

**Comment by FoksVHox** [comment]
There are nobody who used Laravel 5.4 today, as Laravel 5.4 is not supported. I think you should take a look into which versions of Laravel, the Laravel Team support. All versions below Laravel 6 has reached end-of-life.

**Comment by FoksVHox** [comment]
@nWidart What about this, shouldn't we have merged this as well?

**Comment by nWidart** [comment]
Not a fan of this one. The versions array there isn't a list of supported versions, just a matrix of package version -> laravel version.
In case someone is still using laravel 5.6, they know what to use 😅

**Comment by FoksVHox** [comment]
> Not a fan of this one. The versions array there isn't a list of supported versions, just a matrix of package version -> laravel version.
> In case someone is still using laravel 5.6, they know what to use 😅

Oh okay.

**Pull request closed without merging**
