### PR TITLE
Fix view publishing and view cache issue

### PR DESCRIPTION
**Pull request by rabol**
With this PR two issues will be solved

It is possible to publish views using php artisan command and view caching is possible

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks.

It seems like this might already be working before.
```php
        $this->loadViewsFrom(array_merge(array_map(function ($path) {
            return $path . '/modules/$LOWER_NAME$';
        }, \Config::get('view.paths')), [$sourcePath]), '$LOWER_NAME$');
```

and `view.paths` is an array you can customise. 

```php
    'paths' => [
        resource_path('views'),
    ],
```

**Comment by rabol** [comment]
Hi

no, the original did not work as i would add one or more empty directories.

The original implementation add two:
```
<base_dir>/resources/views/modules/<module_name>
<base_dir>/Modules/<Module_name>/Resources/views
```
the first directory path does not exists so therefore the artisan view:cache commands fail

the 'tag' for publishing was equal for all modules which is why the artisan vendor:publish could not figure out what to publish.

**Comment by nWidart** [comment]
I just tested it out and it does work.

The views need to exist under the correct path as per the SP: `$viewPath = resource_path('views/modules/blog');`

image

The views are also properly published using:
```
vendor:publish --tag=views 
```
image

**Comment by rabol** [comment]
But you are using the same tag for all modules so either the wrong or all views will be published - which might not be what the users want

It’s your package, do as you see fit

**Comment by nWidart** [comment]
Indeed, I've added the extra tag, instead of replacing it, which would be a breaking change potentially.

https://github.com/nWidart/laravel-modules/commit/c5c078313ce218bc15accfa7c0054597b84d6893

**Pull request closed without merging**
