### PR TITLE
Fix namespace - Resolved StudlyCase Namespace Generation Issues and App\\ Path

### PR DESCRIPTION
**Pull request by solomon-ochepa**
### Issue Fix:
I have resolved the problem with namespace generation where each word wasn't capitalized properly within the paths.

### Reinstatement of app/ Path:
Acknowledging that a previous pull request removed the "App\" path. This path is essential for consistency and compliance with Laravel and PSR-4 conventions. Hence, the "App\" path has been reinstated to ensure adherence to conventions and maintain compatibility with the Laravel structure.

### Consistency and Compliance:
While the removal of the "App\" path may improve namespace aesthetics, it's crucial to maintain consistency and standards which mandate the use of the "App\" prefix for app/ path. Hence, the "App\" path has been reinstated to ensure compliance.

### Thorough Pull Request Review:
This pull request serves as a reminder of the importance of thoroughly reviewing pull requests before merging. By conducting comprehensive reviews, we can prevent the need for such customizations in the future, saving time and ensuring smoother development processes.

### Micro Commit Format:
Implemented commits in a microformat to facilitate easy readability and reviewing. Each commit focuses on a specific change, enhancing clarity and simplifying the review process.

### Clean, Readable, and Consistent Code:
Emphasizing the importance of maintaining clean, readable, and consistent code throughout the project. By adhering to coding standards and best practices, we can enhance code maintainability and collaboration among team members.

Please review the changes carefully to ensure they align with project requirements and standards before merging. Your feedback is greatly appreciated.

### CODE REVIEW

**Comment by dcblogdev** [comment]
Sorry I have no plans to merge this, it would require a major version change.

the problem you've described is not a problem composer autoloads files from the app folder using `"Modules\\Admin\\": "app/",` this is a common pattern for autoloading.

I was reluctant to change it the first time but did so as it overall did make sense and was part of a major release cycle. 

We try to keep the major versions inline with Laravel versions.

@alissn any thoughts on this?

You can see a real application using the new structure https://github.com/laravel-modules-com/fuse 

also on a breeze demo https://github.com/laravel-modules-com/breeze-demo/tree/main/Modules

**Comment by solomon-ochepa** [comment]
> Sorry I have no plans to merge this, it would require a major version change.
> 
> The problem you've described is not a problem composer autoloads files from the app folder using `"Modules\\Admin\\": "app/",` this is a common pattern for autoloading.
> 
> I was reluctant to change it the first time but did so as it overall did make sense and was part of a major release cycle.
> 
> We try to keep the major versions inline with Laravel versions.
> 
> @alissn any thoughts on this?
> 
> You can see a real application using the new structure https://github.com/laravel-modules-com/fuse
> 
> also on a breeze demo https://github.com/laravel-modules-com/breeze-demo/tree/main/Modules

The PR from @alissn was the root of this problem. At the package level (laravel-module) it's common, but the generated code (modules) should maintain a standard with the Laravel structure and pattern.

Nevertheless, this PR will not require a major version change as you supposed. The structure is the same, the only difference is the missing App\ from the namespace.

@alissn created an update command that can remove the App\\ from the namespace, all we have to do is to reverse the command.

**Comment by solomon-ochepa** [comment]
If you review this PR carefully, there are no major changes. All It does is to add back the `App\` segment to the namespace.

Please, point out the parts that you think will require major changes and I'll amend it as soon as possible.

**Comment by alissn** [comment]
> @alissn any thoughts on this?

@dcblogdev 
Hi,

I am fundamentally against this change, but I cannot understand the reasons behind it. It's not because I made the change; many open-source projects, like Laravel, adhere to this convention.

@solomon-ochepa,

> The PR from @alissn was the root of this problem. At the package level (laravel-module) it's common, but the generated code (modules) should maintain a standard with the Laravel structure and pattern.

I agree with @dcblogdev, we only try to keep this package folder structure with Laravel.
also,I cannot accept your stance on the namespace issue. If there is an article or topic about this with valid resources, please point it out. The community decides on this matter.

**Comment by alissn** [comment]
@solomon-ochepa 

Did you find a reference for the namespace issue that prompted you to create this pull request? I look forward to reviewing it. This weekend, I'll have some free time to read your reference and decide on it.

**Comment by solomon-ochepa** [comment]
> @solomon-ochepa 
> 
> Did you find a reference for the namespace issue that prompted you to create this pull request? I look forward to reviewing it. This weekend, I'll have some free time to read your reference and decide on it.
> 

Hi @alissn, I'm the director of ICT and a senior Software Engineer in my company. I'm not always free during the week.

However, if you need references to backup my PR, will it be approved if I provide one?

I may not know the capacity your operating on, but you are not sounding welcoming at all. How many references did you submitted while removing the app\\ path from the namespace?

Truly, I observed we were finding it difficult to transform lower cases in the namespaces which have leads to the removal of the app\\ path, because at the time we can't transform it into App\\.

Now, I've created a solution and suggest we correct the issue now. What's difficult to understand here?

Instead of welcoming the PR that correct and improve the package, you are more than ready to fight me.

If you guys don't need our contributions anymore, then it's okay.

@alissn 
May I ask you one final question please? What was you reason for removing the app\\ from the namespace? Be sincere.

**Comment by solomon-ochepa** [comment]
> I look forward to reviewing it. This weekend, I'll have some free time to read your reference and decide on it.
> 

@alissn Are you in charge of reviewing PR and making decisions now? You sound so authoritative! Like you decide what happen here!!

Anyway, have you check the Laravel official `composer.json` file? If we have "App\\": "app/", then why are we having it removed in ours?

The App\\ in the namespace make it easy to location classes and files in the project.

Please, and please. Arguments and claiming authority will not lead us anywhere. Instead why not focus on the benefits each PR is bringing to the table and how we can collaborate to make a better world. Open source is all about better life and a better world, why are we here fighting?

Let's not personalized things here, that's not the spirit in open source!

**Comment by alissn** [comment]
@solomon-ochepa,

Hi there,

Do you think I'm an intern or junior in my own company? 😁 I wanted to check out the website of your company, but it seems to be experiencing some issues. If [this](http://www.okitechnologies.com/) is your site, please address the problems first as it's not loading properly. 😏

On another note, I only create merge requests, and if they're closed, I respect the maintainer's decision. if accepted because it's ok for maintainer's after fix bugs. There's no need to repeatedly question why it wasn't merged or why it was closed. Ultimately, it's up to @dcblogdev to decide whether to merge or not.

I'm not here to argue with you. I simply don't have the time to review 109 changes, and even if I did, my review wouldn't have much impact because you seem to disagree with the code style of this package. For instance, in the file `src/Commands/Make/ChannelMakeCommand.php`, you removed the docBlock, but in [this PR](https://github.com/nWidart/laravel-modules/pull/1803/commits/52ade52fb601da39118d33975b157be556d1a162), a docBlock was added to the stub. 

I've read your comments, but many of them seem to address issues that were already discussed in my previous merge requests.

**Comment by dcblogdev** [comment]
I'm closing this, it covers more than adding an App namespace, it adds new methods that don't have tests, removed return types,  renames the path to where stubs are published.

Please bear in mind in the future try not to do too many different things in a single pull request.

**Comment by solomon-ochepa** [comment]
I'll update these issues you've pointed out and resubmit the PR.

Thanks for the review.

**Comment by solomon-ochepa** [comment]
> I'm closing this, it covers more than adding an App namespace, it adds new methods that don't have tests, removed return types, renames the path to where stubs are published.
> 
> Please bear in mind in the future try not to do too many different things in a single pull request.

You are right. I've learned a lot about micro-commit and PR due to this comment alone. Thank you.

**Pull request closed without merging**
