### PR TITLE
Add command for creating a component view

### PR DESCRIPTION
**Pull request by FoksVHox**
*Needs some more work, as it only creates the view and not the class...* 

Solves #1086

### CODE REVIEW

**Comment by FoksVHox** [comment]
@nWidart I'm not sure what you think about changing the `GeneratorCommand`, so it looks more like the one form Laravel, the reason being that I need to create a component class for the views.

**Comment by nWidart** [comment]
hi @FoksVHox , what exactly would change? What would it allow that it can't do now?

Thanks!

**Comment by FoksVHox** [comment]
> hi @FoksVHox , what exactly would change? What would it allow that it can't do now?
> 
> Thanks!

Right now I can't make the Component Class which is used for them in Laravel. I want to change it, so I'm able to create the Component Class.

**Comment by nWidart** [comment]
I understand, but what is it that blocks you from creating the component class, specifically?

**Comment by FoksVHox** [comment]
> I understand, but what is it that blocks y

As far as I'm aware of I'm not able to create more files inside the `getTemplateContents` function.

**Comment by nWidart** [comment]
Ah ok I see. You could have multiple sub commands that are being called by the main generate one for this PR, but that might be too hacky. So if you have a good solution by using laravel's structure, while keeping all existing commands working, why not.

**Comment by FoksVHox** [comment]
> Ah ok I see. You could have multiple sub commands that are being called by the main generate one for this PR, but that might be too hacky. So if you have a good solution by using laravel's structure, while keeping all existing commands working, why not.
I'll play around with it

**Comment by FoksVHox** [comment]
Closing in favor of #1110

**Pull request closed without merging**
