### PR TITLE
Routes and Laravel Mix

### PR DESCRIPTION
**Pull request by KABBOUCHI**
1- Change routes structure

2- Add ``webpack.mix.js`` stub file

Register single module
```diff
let mix = require('laravel-mix');

+ require('./Modules/Blog/webpack.mix.js');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

```

Auto register all webpack files

```diff
let mix = require('laravel-mix');

+ let fs = require('fs-extra');
+
+ let modules = fs.readdirSync('Modules');
+ 
+ if (modules && modules.length > 0)
+ {
+     modules.forEach((module) => {
+         let path = `./Modules/${module}/webpack.mix.js`;
+         if (fs.existsSync(path)) {
+             require(path);
+         }
+     });
+ }

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

```

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply!
This looks good! Could you please send a new PR only with the changes related to webpack?
This is because the route file changes is a breaking change.

Thank you!

**Comment by KABBOUCHI** [comment]
@vahidalvandi plz check here: https://nwidart.com/laravel-modules/v3/basic-usage/compiling-assets

We end up using a different way

**Comment by xavi7th** [comment]
@KABBOUCHI I think the way you proposed to use is waaaaaaaay better. That way you dont have to run multiple mix watch instances. I currently use your method of auto register all webpack files and it's lots easier IMHO.

**Comment by KABBOUCHI** [comment]
@xavi7th yeah its easier, but perhaps you want to extract the module and re-use it, so the node packages should be live with in the module.

Both have pros and cons, use the best for you.

**Pull request closed without merging**
