### PR TITLE
hotfix install packages if exist

### PR DESCRIPTION
**Pull request by Quiss**
if require || require-dev is empty, composer ask to enter a package:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Search for a package:
```

### CODE REVIEW

**Comment by nWidart** [comment]
Hello,

Thank you for the contribution.

To make sure I understand. If there was nothing in require or require-dev, composer was asking what to require?

**Comment by Quiss** [comment]
@nWidart yeap.

**Comment by Quiss** [comment]
@nWidart WTR:
```
"require": {
        "lord/laroute": "2.*"
    },
    "require-dev": {},
```

php artisan module:update ModuleName

**Comment by nWidart** [comment]
Cool, thank you! 👍

**Pull request merged**
