### PR TITLE
Update config.php

### PR DESCRIPTION
**Pull request by solomon-ochepa**
Update the following config keys to a more generic phrase

`MODULES_VENDOR_NAME` instead of `MODULES_NAME`,
`MODULES_VENDOR_EMAIL` instead of `MODULES_EMAIL`.

### CODE REVIEW

**Comment by nWidart** [comment]
Hi,

Module name and module vendor name are not the same thing in my opinion.
Module name could be "invoice" but the developer is called "john doe".

**Comment by solomon-ochepa** [comment]
> Hi,
> 
> Module name and module vendor name are not the same thing in my opinion.
> Module name could be "invoice" but the developer is called "john doe".

You are correct, and that's the exact reason why this PR was submitted.

Take a look at the code changes again.

The key `MODULE_NAME` is wrong, it should be `MODULE_VENDOR_NAME` instead!

Thanks for noticing the correction.

**Comment by dcblogdev** [comment]
I think `MODULES_AUTHOR_NAME` and `MODULES_AUTHOR_EMAIL` would make more sense, to make it clear its for the author of the module.

**Comment by dcblogdev** [comment]
Also change `MODULES_VENDOR` to `MODULE_VENDOR` so they all match the intention to add details to a module.

**Pull request merged**
